### ISSUE TITLE
Create unit-tests for `add_password` operation in `PasswordStore`

### ISSUE THREAD

**Issue by SonuBardai** [SonuBardai/lockbox#11]
Add tests for the `add_password` operation in the `PasswordStore`

`add_password`: https://github.com/SonuBardai/lockbox/blob/main/src/store/mod.rs#L69-L82
References to other tests: https://github.com/SonuBardai/lockbox/blob/main/src/store/mod.rs#L116-L293

**Comment by postmeback** [comment]
Can i contribute here ?

**Comment by SonuBardai** [comment]
@postmeback Sure! All contributions are welcome. I have updated the description with some details, hope that helps. Feel free to create a pull request 👍

**Comment by postmeback** [comment]
Sure, will pick it up and contribute.
