### ISSUE TITLE
Prerequisites required

### ISSUE THREAD

**Issue by IshanGrover2004** [SonuBardai/lockbox#73]
State all the "prerequisites library list" which must be installed for running project succesfully

**Comment by SonuBardai** [comment]
@IshanGrover2004 Thanks for reporting this issue. I hope [this](https://github.com/SonuBardai/lockbox#install) addition to the README helps clarify the dependencies.

**Comment by IshanGrover2004** [comment]
Really appreciated for your help❤️
Thanks for coming up with easy & lovely project
