### ISSUE TITLE
`lockbox show` should also copy the password

### ISSUE THREAD

**Issue by SonuBardai** [SonuBardai/lockbox#87]
Currently, this command simply displays the password. While this functionality is useful, I believe it could be further improved by integrating an automatic ‘copy to clipboard’ feature.

The proposed enhancement would work as follows: upon execution of the lockbox show command, the password would also automatically copied to the user’s clipboard. Importantly, this automatic copy feature should be implemented to function irrespective of whether the --reveal flag is passed.

**Comment by SonuBardai** [comment]
Hey @CouldBeFree! Yup, we want to automatically copy the password to the clipboard when show is run and the password is found.

**Comment by CouldBeFree** [comment]
@SonuBardai that's clear, but as far as I see, the `show` command returns the list of passwords. So a user in some way should be able to select which password he wants to copy. What do you think?

**Comment by CouldBeFree** [comment]
I apologize for my inattention, I mixed up the commands.
@SonuBardai  I can work on this

**Comment by CouldBeFree** [comment]
@SonuBardai can I make the password public, because I can't get access to the password field in the `PasswordEntry` struct?

```
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct PasswordEntry {
    pub service: String,
    pub username: Option<String>,
    password: String,
}

pub fn show_password<W: Write>(
    writer: &mut W,
    password_store: &mut PasswordStore,
    service: String,
    username: Option<String>,
) -> anyhow::Result<()> {
    let password = password_store.load()?.find(service, username);
    if let Some(password) = password {
        password.print_password(writer, Some(MessageType::Info));
        match copy_to_clipboard(password.password) {
            Ok(_) => print(
                writer,
                "(Password copied to clipboard)",
                None,
            ),
            Err(err) => {
                print(writer, &format!("(Failed to copy password to clipboard: {err})"), Some(MessageType::Warning))
            }
        }
    } else {
        writeln!(writer, "Password not found")?;
    }
    Ok(())
}
```

**Comment by SonuBardai** [comment]
I don't think making password public is a good idea. We don't want to make master password or any password field accessible outside the enclosing struct. Eitherway, feel free to create a PR for this. That will be easier to review all the changes. @CouldBeFree

**Comment by SonuBardai** [comment]
You can do the copy inside the `find` function. Or, you can make a new `copy` function inside the `PasswordStore` and latch it onto the password store operations. Something like this: `password_store.load().find(...).copy()`
